### ISSUE TITLE
Script brings error on mac

### ISSUE THREAD

**Issue by YourAverageMo** [YourAverageMo/auto-silence-cut#2]
Ahhhhh interesting! I just tested it out on the paid version and no luck, but theres a VERY good chance that it's user error on my part lol! I will keep toying around with it. This is the console log when I try to open auto-editor.py

`Traceback (most recent call last):
  File "/Library/Application Support/Blackmagic Design/DaVinci Resolve/Fusion/Scripts/Utility/auto_editor.py", line 620, in <module>
    audio_track_count = diff_audio_tracks()
                        ^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Blackmagic Design/DaVinci Resolve/Fusion/Scripts/Utility/auto_editor.py", line 279, in diff_audio_tracks
    creationflags=subprocess.CREATE_NO_WINDOW)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'subprocess' has no attribute 'CREATE_NO_WINDOW'`

_Originally posted by @randyrektor in https://github.com/YourAverageMo/auto-silence-cut/issues/1#issuecomment-2486709975_

**Comment by YourAverageMo** [comment]
This is a good first issue if anyone wants to take a look. i mostly work on windows so don't have much mac experience. However, i do believe it has something to do with the way the 'subprocess' module works on mac since mac uses terminal not cmd.

there may be a universal alternative to 'CREATE_NO_WINDOW' that i just don't know about, if not a simple work around could be to look at the users OS and have a separate process for macs.
